####
# command pallete > Open Setting JSON
# rest-client.environmentVariables

####
@host = http://localhost:8083
@imagename = mmodelshare
####
GET {{host}}/mcm/v1/images
Authorization: bearer {{edgeToken}}


####
POST {{host}}/mcm/v1/images
Content-Type: multipart/form-data; boundary=$Boundary$
Authorization: Bearer {{edgeToken}}

--$Boundary$
Content-Disposition: form-data; name="image"; filename="{{imagename}}-v1.tar"

< /Users/jeremy/Workspace/hz-demo/mmodelshare/deploy/{{imagename}}-v1.tar
--$Boundary$--


####
POST {{host}}/mcm/v1/containers
Content-Type: application/json
Authorization: Bearer {{edgeToken}}

{
  "env": {
    "AUTHORIZATION_KEY": "test",
    "MCM.BASE_API_PATH": "/{{imagename}}/v1",
    "MCM.WEBSOCKET_SUPPORT": "false",
    "MODEL_URL": "http://url",
    "MODEL_VERSION": "1.0.0",
    "MAX_EVENT_COUNT": "5"
  },
  "id": "{{imagename}}-v1",
  "image": "{{imagename}}-v1",
  "imageId": "{{imagename}}-v1",
  "name": "{{imagename}}-v1",
  "state": "started"
}

###
GET {{host}}/{{clientId}}/{{imagename}}/v1/models


####
DELETE {{host}}/{{clientId}}/{{imagename}}/v1/models/default
Authorization: Bearer test


####
POST {{host}}/{{clientId}}/{{imagename}}/v1/models
Content-Type: multipart/form-data; boundary=$Boundary$
Authorization: Bearer test

--$Boundary$
Content-Disposition: form-data; name="metadata"; 

{
  "name": "default",
  "version": "1.0.0",
  "mimeType": "application/zip"
}
--$Boundary$
Content-Disposition: form-data; name="file"; filename="default"

< /Users/jeremy/Workspace/hz-demo/mmodelshare/deploy/{{imagename}}-v1.tar
--$Boundary$--


####
GET {{host}}/{{clientId}}/{{imagename}}/v1/classificationEvents

####
POST {{host}}/{{clientId}}/{{imagename}}/v1/classificationEvents
Content-Type: application/json
Authorization: Bearer test

{
  "modelId": "default",
  "score": 30,
  "classification": "shower cap",
  "image": "local_image_path"
}

####