@host = http://localhost:8083

@edgeToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNDY2Njg4Nzk5MDg4NzQ2NDk2IiwianRpIjoiYm5KbmdrYW5KbERVV1RLSEhJbEJNUn5fMmdnaUxZZzRSaHV-dnN6QTg3WSIsImNsaWVudF9pZCI6ImQ0NTJkZWM2LTA2NzctNDBiYi04MmZhLWMyNGE1OWY5NzZmZiIsImF6cCI6ImQ0NTJkZWM2LTA2NzctNDBiYi04MmZhLWMyNGE1OWY5NzZmZiIsImlzcyI6Imh0dHBzOi8vbWlkLm1pbWlrMzYwLmNvbS9tSUQvdjEvb2F1dGgvdG9rZW4iLCJub2RlX2lkIjoiYzdiMDY2NmY3ZjlkYWNjM2E2OWE2ZDljMTE0MDYxZGRlMjM1OWFjODlmNjBiMWE2N2Y0ZGNkYTQiLCJhdWQiOlsiaHR0cHM6Ly9taW1payIsImh0dHBzOi8vbXN0Lm1pbWlrMzYwLmNvbS9tU1QvdjEvY2xpZW50cy9HZW5lcmljLWVkZ2UiXSwic2NvcGUiOiJvcGVuaWQgZWRnZTptY20gZWRnZTpjbHVzdGVycyBlZGdlOmFjY291bnQ6YXNzb2NpYXRlIGVkZ2U6YWNjb3VudDp1bmFzc29jaWF0ZSBlZGdlOnJlYWQ6YWNjb3VudGtleSIsImlhdCI6MTYxMTk2MDQxMiwiZXhwIjoxNjI3NTEyNDEyfQ.RCwVOG-lqcAkZwelTu4LGteba8M1xySSpF9F1lh4CMo

@clientId = d452dec6-0677-40bb-82fa-c24a59f976ff

@apiKey = 1234

###
POST {{host}}/mcm/v1/images
Content-Type: multipart/form-data; boundary=$Boundary$
Authorization: Bearer {{edgeToken}}

--$Boundary$
Content-Disposition: form-data; name="image"; filename="mmodelshare-v1.tar"

< ../deploy/mmodelshare-v1.tar
--$Boundary$

###
POST {{host}}/mcm/v1/containers
Content-Type: application/json
Authorization: Bearer {{edgeToken}}

{
  "env": {
    "MCM.BASE_API_PATH": "/modelshare/v1",
    "MCM.DB_ENCRYPTION_SUPPORT": "false",
    "MCM.WEBSOCKET_SUPPORT": "true",
    "API_KEY": "1234",
    "WEBHOOK_URL": "https://httpbin.org/post"
  },
  "image": "mmodelshare-v1",
  "name": "mmodelshare-v1"
}

###
GET {{host}}/mcm/v1/containers
Content-Type: application/json
Authorization: Bearer {{edgeToken}}

###
DELETE {{host}}/mcm/v1/containers/{{clientId}}-mmodelshare-v1
Content-Type: application/json
Authorization: Bearer {{edgeToken}}


###
POST {{host}}/{{clientId}}/modelshare/v1/models
Content-Type: multipart/form-data; boundary=$Boundary$
x-api-key: {{apiKey}}

--$Boundary$
Content-Disposition: form-data; name="file"; filename="mmodelshare-v1.tar"

< ../deploy/mmodelshare-v1.tar
--$Boundary$
Content-Disposition: form-data; name="metadata";

{
  "name": "mmodelshare-v1.tar",
  "version": "1.3.3",
  "description": "microservices",
  "mimeType":"application/tar"
}
--$Boundary$--

###
GET {{host}}/{{clientId}}/modelshare/v1/models

###
DELETE {{host}}/{{clientId}}/modelshare/v1/models/mmodelshare-v1.tar
x-api-key: {{apiKey}}

###
POST {{host}}/{{clientId}}/modelshare/v1/classificationEvents
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "modelId": "mmodelshare-v1.tar",
  "score": 0,
  "classification": "motion",
  "extras": [
    {
      "id": "c66a770c-6a35-11eb-9439-0242ac130002",
      "path": "/usr/lib/videos/example.mp4",
      "mimeType": "video/mp4"
    }
  ]
}

###
GET {{host}}/{{clientId}}/modelshare/v1/classificationEvents
Content-Type: application/json