name: mimik
api:
  name: mmodelshare
  swagger: node_modules/swagger-mmodelshare/mmodelshare-api-swagger.yml
  controllerPath: ../src/controllers
  securityHandlerPath: ../src/handlers
  outputPath: ./build
package:
  imageName: mmodelshare
  imageIndexFilePath: ./build/index.js
  outputFolder: ./deploy
